#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

prebuild() {
    rm -rf dist
    cp -rf src dist && /usr/bin/find dist -name '*.spec.ts' | xargs rm -f
    cat tsconfig.json | jq 'del(.include, .compilerOptions.outDir)' > dist/tsconfig.json
    cp README.md LICENSE package.json dist
}

build() {
    cd dist
    rm example.ts
    tsc -p .
    rm tsconfig.json
    cd ..
}

"$@"
